name = "CCCE Modded"
author = "verdantfuture"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e31eae72a264723d2871de280bd392d1fb206198cb7f85c160bb9ce9f4210c69"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.93"
